name: Build and Deploy

on:
  push:
    branches: [master] # master 分支提交时触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 运行环境
    steps:
      - name: 签出代码
        uses: actions/checkout@v2 # 使用 v2 版本
      - name: 安装 Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # 明确指定 Node.js 14.x 版本
      - name: 安装依赖
        run: npm install
      - name: 前端项目打包
        run: npm run build
      - name: 测试 SSH 连接
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key root@${{ secrets.REMOTE_HOST }} echo "SSH connection successful"
      - name: 发布到腾讯云
        uses: easingthemes/ssh-deploy@v2.0.7
        with:
          REMOTE_HOST: '${{ secrets.REMOTE_HOST }}'
          REMOTE_USER: '${{ secrets.REMOTE_USER }}'
          TARGET: '/www/wwwroot/zhj.com'
          SOURCE: 'dist/'
          ARGS: '-avzr --delete'
          SCRIPT: |
            # 添加额外的日志输出
            echo "Starting rsync..."
            rsync -avzr --delete ./dist/ root@${{ secrets.REMOTE_HOST }}:/www/wwwroot/zhj.com
            echo "Rsync completed."

        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
